### ISSUE TITLE
Add a AlertifyKernelRequestListener onKernelResponse to dispatch alerts automatically

### ISSUE THREAD

**Issue by lenybernard** [Troopers/AlertifyBundle#33]
Today, to make alerts pop, we need to add this line in the layout:

```
twig
{{ app.request|alertify }}
```

The AlertifyKernelRequestListener would listen `kernel.response` event and automatically inject needed alerts

**Comment by paulandrieux** [comment]
:+1: it can be inspirated by the WebDebugToolbarListener that inject the SF toolbar in any response.
