### ISSUE TITLE
Overriding Templates

### ISSUE THREAD

**Issue by llaville** [Troopers/AlertifyBundle#73]
Hello,

I've just tested this bundle with toastr backend, and I've wanted to used some options that are not provided by default bundle template: `Resources\views\toastr.html.twig` 

I used Symfony 3.4, and I overrides templates such as described in [SF blog](https://symfony.com/blog/new-in-symfony-3-4-improved-the-overriding-of-templates).

Checking the twig templates with console command  `debug:twig`  I got 

```
  @TroopersAlertify    - templates/bundles/TroopersAlertifyBundle                                     
                       - vendor/troopers/alertify-bundle/Troopers/AlertifyBundle/Resources/views      
                                                                                                      
  @!TroopersAlertify   - vendor/troopers/alertify-bundle/Troopers/AlertifyBundle/Resources/views      

```

I copied the default  `toastr.html.twig` into  `templates/bundles/TroopersAlertifyBundle` folder and change it a few as follow : 

``` twig
{# Check & auto repair #}
{% if layout not in ['top-right', 'top-left', 'top-full-width', 'bottom-right', 'bottom-left', 'bottom-full-width'] %}
    {% set layout = 'top-right' %}
{% endif %}

<script type="text/javascript">
    (function() {
      var delay;

      delay = function(ms, func) {
        return setTimeout(func, ms);
    };

    //
    toastr.options = {
        positionClass    : 'toast-{{ layout }}', //top-right, top-left, top-full-width, bottom-right, bottom-left, bottom-full-width
        closeButton    : {{ options.closeButton|default('false') }},
        debug          : {{ options.debug|default('false') }},
        onclick        : {{ options.onclick|default('null') }},
        showDuration   : {{ options.showDuration|default('20000') }},
        hideDuration   : {{ options.hideDuration|default('1000') }},
        timeOut        : {{ options.timeOut|default('5000') }},
        extendedTimeOut: {{ options.extendedTimeOut|default('1000') }},
        showEasing     : '{{ options.showEasing|default('swing') }}',
        hideEasing     : '{{ options.hideEasing|default('linear') }}',
        showMethod     : '{{ options.showMethod|default('fadeIn') }}',
        hideMethod     : '{{ options.hideMethod|default('fadeOut') }}',
        progressBar    : {{ options.progressBar|default('false') }},
        containerId    : '{{ options.containerId|default('toast-container') }}'
    };

    var body = "{{ body|replace({'\r\n|\n|\r': '<br/>'})|raw|trans({}, translationDomain|default('messages')) }}";
    delay({% if timeout is defined and timeout != null %} {{ timeout }}{% else %} 1000{% endif %} , function() {
        return toastr.{{ type }}(body,"{{ title|default(("alert."~type~".label")|trans({}, translationDomain|default('messages'))) }}");
    });

}).call(this);
</script>

```

The template was not used until I change a little syntax call in `vendor/troopers/alertify-bundle/Troopers/AlertifyBundle/Handler/AlertifySessionHandler.php`, line [58](https://github.com/Troopers/AlertifyBundle/blob/master/Handler/AlertifySessionHandler.php#L58)

With version 3.0.9 (installed under Symfony 3.4.6) we have 

``` diff
$renders[$type.$key] = $twig->render(
-  'TroopersAlertifyBundle::'.$parameters['engine'].'.html.twig',
+  '@TroopersAlertify/'.$parameters['engine'].'.html.twig'
    $parameters
)
```

Did  I missed something, or just misunderstood how to custom it ?
Thanks in advance 
Laurent

**Comment by lenybernard** [comment]
Hi,

First, as I see, you try to override the template in the symfony4 way by using the new architecture (`templates` folder). If you're in Symfony v3.4, you need to follow the documentation for this version [https://symfony.com/doc/3.4/templating/overriding.html[(https://symfony.com/doc/3.4/templating/overriding.html)

But you're right, if you're using the logical paths (with the @), the system apparently succeed to find the `toastr.html.twig` in the symfony4 `templates` folder.

I let you test your modification with the normal directory structure (for a 3.4 project) and please then send a pull request.

Bye !

**Comment by llaville** [comment]
Ok Will do submit a PR. 
BTW, I can tell you that it work fine with Symfony 3.4 and the new `templates` folder architecture.

Just finished to implement a real implementation !

Thanks for quick reply :-)

**Comment by llaville** [comment]
Ok I confirm, that syntax with @ run as expected with Symfony 3.4 and ready for SF 4 !!!

Confirm with `debug:twig` command 

```
  @TroopersAlertify      - app/Resources/TroopersAlertifyBundle/views
                         - /templates/bundles/TroopersAlertifyBundle
                         - vendor\troopers\alertify-bundle\Troopers\AlertifyBundle/Resources/views
```

PR will follow
